### ISSUE TITLE
App crashes after selecting image file from file manager.

### ISSUE THREAD

**Issue by PrakharAwasthi0** [idoideas/StickerMaker-for-Whatsapp#3]
"Unfortunately the app has stopped working" is the message which i get after selecting any file be it .webp or .png or .jpg

**Comment by idoideas** [comment]
Hey, I'd like to help you with that!

Do you have the stacktrace of the crash?

**Comment by yunusmete** [comment]
Same here. Both emulator(8.1) and real device(5.0) are crashed. Here is the stacktrace of crash:
``12-01 18:30:29.602 2341-32034/? D/SplitWindowPolicy: topRunningActivity=ActivityInfo{11ad5cd5 co.....WhatsAppBasedCode.StickerPackDetailsActivity}, taskId=18, activityType=0, bIsSplit=false
12-01 18:30:29.606 316-20909/? D/libc-netbsd: res_queryN name = pagead2.googlesyndication.com succeed
12-01 18:30:29.610 20748-20748/com.idoideas.stickermaker D/ContextHelper: convertTheme. context->name=com.idoideas.stickermaker themeResourceId=2131755014
12-01 18:30:29.612 20748-20766/com.idoideas.stickermaker W/Ads: Got on activity created
12-01 18:30:29.617 20748-20748/com.idoideas.stickermaker I/PhoneWindow: [generateLayout] setColorNavigationBar => color=0x ff000001
12-01 18:30:29.618 20748-20748/com.idoideas.stickermaker D/PhoneWindowEx: [LMJ][PWEx][generateLayout] setNavigationBarColor2 : colors=0xfff5f5f5
12-01 18:30:29.618 20748-20748/com.idoideas.stickermaker I/PhoneWindow: [setNavigationBarColor2] color=0x fff5f5f5
12-01 18:30:29.649 20748-20748/com.idoideas.stickermaker W/ResourceType: Failure getting entry for 0x7f07005d (t=6 e=93) (error -75)
12-01 18:30:29.654 20748-20748/com.idoideas.stickermaker D/AndroidRuntime: Shutting down VM
12-01 18:30:29.656 20748-20748/com.idoideas.stickermaker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.idoideas.stickermaker, PID: 20748
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.idoideas.stickermaker/com.idoideas.stickermaker.WhatsAppBasedCode.StickerPackDetailsActivity}: android.view.InflateException: Binary XML file line #133: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
        at android.app.ActivityThread.access$800(ActivityThread.java:148)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5272)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
     Caused by: android.view.InflateException: Binary XML file line #133: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.idoideas.stickermaker.WhatsAppBasedCode.StickerPackDetailsActivity.onCreate(StickerPackDetailsActivity.java:80)
        at android.app.Activity.performCreate(Activity.java:5977)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365) 
        at android.app.ActivityThread.access$800(ActivityThread.java:148) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5272) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.idoideas.stickermaker.WhatsAppBasedCode.StickerPackDetailsActivity.onCreate(StickerPackDetailsActivity.java:80) 
        at android.app.Activity.performCreate(Activity.java:5977) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365) 
        at android.app.ActivityThread.access$800(ActivityThread.java:148) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5272) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 
     Caused by: android.content.res.Resources$NotFoundException: Resource "com.idoideas.stickermaker:drawable/btn_blue" (7f07005d)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f07005d a=-1 r=0x7f07005d}
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2431)
        at android.content.res.Resources.loadDrawable(Resources.java:2371)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
        at android.view.View.<init>(View.java:3737)
        at android.view.ViewGroup.<init>(ViewGroup.java:491)
        at android.widget.FrameLayout.<init>(FrameLayout.java:115)
        at android.widget.FrameLayout.<init>(FrameLayout.java:111)
        at android.widget.FrameLayout.<init>(FrameLayout.java:107)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.idoideas.stickermaker.WhatsAppBasedCode.StickerPackDetailsActivity.onCreate(StickerPackDetailsActivity.java:80) 
        at android.app.Activity.performCreate(Activity.java:5977) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365) 
        at android.app.ActivityThread.access$800(ActivityThread.java:148) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5272) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 
12-01 18:30:29.658 1093-1113/? W/ActivityManager:   Force finishing activity com.idoideas.stickermaker/.WhatsAppBasedCode.StickerPackDetailsActivity
12-01 18:30:29.662 1093-1113/? W/ActivityManager:   Force finishing activity com.idoideas.stickermaker/.WhatsAppBasedCode.StickerPackListActivity``

**Comment by idoideas** [comment]
I see the issue is that it doesn't find the buttons XMLs. It's because the drawables are in the [v24 folder](https://github.com/idoideas/StickerMaker-for-Whatsapp/tree/master/app/src/main/res/drawable-v24), which works only from API 24 (Android 7.0) and beyond.

I'll try to fix it in the git tomorrow, but meanwhile try it on a 7.0+ device, or try moving the files to the generic `drawable` folder.

**Comment by nandosilvajr** [comment]
It's same with me.

**Comment by Norman191** [comment]
Yes, App crashes when selecting an image

**Comment by Norman191** [comment]
Edit: 
I solved this , by using (background: #color_code) for buttons, instead of using the xml .
Now everything works fine.
Thanks.

**Comment by ga4pk** [comment]
idoideas.... hi sir help me.
"Unfortunately the app has stopped working" is the message which i get after selecting any file be it .webp or .png or .jpg
![screenshot_20190119-100522](https://user-images.githubusercontent.com/46834859/51422527-e07e5000-1bd1-11e9-8738-65d3825df36f.png)

please solve issue

**Comment by Norman191** [comment]
@GabbasBwp just look in logcat => error section, to see where the problem starts
