### ISSUE TITLE
Problem changing  playstore link but no json file founded

### ISSUE THREAD

**Issue by NewGove** [idoideas/StickerMaker-for-Whatsapp#4]
I want to change the app store link  that make you go to the app when clicking on sticker on whatsapp 
and also i want to preload some stickers there is a way to do it without zip file ?

**Comment by NewGove** [comment]
tried to put the zip on the assets folder then call the method importZipFileToStickerPack2 on the start of the app

`
   public static void importZipFileToStickerPack2(Context context){
        String zipPath = "assets/app.zip";
        parseZip pz = new parseZip(context, zipPath);
        pz.execute();
    }

`

i put the zip folder (created from the app ) on the assets folder with this name (app.zip) 
but got this dialog : The zip file that was imported is not a proper sticker pack file

**Comment by idoideas** [comment]
Hey!

You did correctly, it's just that that's not how you access the Assets folder :)

Your path should be:

`String zipPath = "file:///android_asset/app.zip";`

Also notice that the app should only accept Zip files that are working by its rules (and by that, I mean Zip files that were created from it).

**Comment by NewGove** [comment]
android_asset is the name of the folder cuz i named it just assets 
thank you so mush for you respond i appreciate it

**Comment by idoideas** [comment]
No, `android_asset` is the constant for Android's Uri for the Assets folder of the app.

Sure, I'll help any time. :)

**Comment by NewGove** [comment]
Still the same problem this is what i did on DataArchiver 


public static void importZipFileToStickerPack2(Context context){
        String zipPath = "file:///android_asset/app.zip";
        parseZip pz = new parseZip(context, zipPath);
        pz.execute();
    }

then call the function inside on create of StickerPackListActivity like this 
`  DataArchiver.importZipFileToStickerPack2(StickerPackListActivity.this);
`

and this is where i putted my zip file 

https://i.imgur.com/meiSmud.png

ps: the zip file i exported it from the app like it was just i changed the name

**Comment by idoideas** [comment]
Hey, I'd like to help.

Please try to add `e.printStackTrace()` in the `catch` in `doInBackground` of `parseZip`, and send the stacktrace here :)

**Comment by NewGove** [comment]
```
11-28 21:42:26.167 20454-20508/com.xpresse.maker W/System.err: java.lang.NullPointerException
11-28 21:42:26.167 20454-20508/com.xpresse.maker W/System.err:     at java.io.File.<init>(File.java:340)
11-28 21:42:26.167 20454-20508/com.xpresse.maker W/System.err:     at com.xpresse.maker.DataArchiver$parseZip.doInBackground(DataArchiver.java:352)
11-28 21:42:26.167 20454-20508/com.xpresse.maker W/System.err:     at com.xpresse.maker.DataArchiver$parseZip.doInBackground(DataArchiver.java:289)
11-28 21:42:26.168 20454-20508/com.xpresse.maker W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
11-28 21:42:26.168 20454-20508/com.xpresse.maker W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-28 21:42:26.168 20454-20508/com.xpresse.maker W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
11-28 21:42:26.168 20454-20508/com.xpresse.maker W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-28 21:42:26.168 20454-20508/com.xpresse.maker W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-28 21:42:26.168 20454-20508/com.xpresse.maker W/System.err:     at java.lang.Thread.run(Thread.java:761)
11-28 21:42:26.199 16391-16403/? W/Finsky: [809] com.google.android.finsky.billing.iab.q.a(161): com.xpresse.maker: No account found.
11-28 21:42:26.201 16391-16408/? W/Finsky: [810] com.google.android.finsky.billing.iab.q.a(161): com.xpresse.maker: No account found.
11-28 21:42:26.202 16391-16912/? W/Finsky: [839] com.google.android.finsky.billing.iab.q.a(161): com.xpresse.maker: No account found.
11-28 21:42:26.204 16391-16403/? W/Finsky: [809] com.google.android.finsky.billing.iab.q.a(161): com.xpresse.maker: No account found.
11-28 21:42:26.206 16391-16408/? W/Finsky: [810] com.google.android.finsky.billing.iab.q.a(161): com.xpresse.maker: No account found.
11-28 21:42:26.206 20454-20454/com.xpresse.maker W/BillingClient: Even billing API version 3 is not supported on this device.

```

**Comment by idoideas** [comment]
It seems like it can't find the directory of the file.

It's kinda late over here so I'll try to look at it tomorrow, ok?

**Comment by NewGove** [comment]
okey thank you idoideas ur so kind
